config/routes.rb
#FatFreeCRM::Application.routes.draw do
#  FatFreeCRM::Application.routes.draw do
Rails.application.routes.draw do
  Rails.application.routes.draw do
    scope Setting.base_url.to_s do
      namespace :admin do
        resources :products do
          collection do
            get :search
            post :auto_complete
          end
          member do
            get :confirm
          end
        end
      end
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many    :product_assets, :dependent => :destroy

  validates_presence_of :name

end

app/models/product_asset.rb
class ProductAsset < ActiveRecord::Base
  belongs_to :product
  belongs_to :asset, :polymorphic => true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController
  before_filter :set_current_tab
  before_filter :auto_complete, :only => :auto_complete

  # GET /admin/products
  # GET /admin/products.xml                                                   HTML
  #----------------------------------------------------------------------------
  def index
    @products = get_products

    respond_to do |format|
      format.html # index.html.haml
      format.js   # index.js.rjs
      format.xml  { render :xml => @products }
    end
  end

  # GET /admin/products/new
  # GET /admin/products/new.xml                                               AJAX
  #----------------------------------------------------------------------------
  def new
    @product = Product.new()

    respond_to do |format|
      format.js   # new.js.rjs
      format.xml  { render :xml => @product }
    end
  end

  # GET /admin/products/1/edit                                                AJAX
  #----------------------------------------------------------------------------
  def edit
    @product = Product.find(params[:id])

    if params[:previous] =~ /(\d+)\z/
      @previous = Product.find($1)
    end

  rescue ActiveRecord::RecordNotFound
    @previous ||= $1.to_i
    respond_to_not_found(:js) unless @product
  end

  # POST /admin/products
  # POST /admin/products.xml                                                  AJAX
  #----------------------------------------------------------------------------
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        @products = Product.find(:all)
        format.js   # create.js.rjs
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.js   # create.js.rjs
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/products/1
  # PUT /admin/products/1.xml                                                 AJAX
  #----------------------------------------------------------------------------
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.js   # update.js.rjs
        format.xml  { head :ok }
      else
        format.js   # update.js.rjs
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:js, :xml)
  end

  # GET /admin/products/1/confirm                                             AJAX
  #----------------------------------------------------------------------------
  def confirm
    @product = Product.find(params[:id])

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:js, :xml)
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.xml                                              AJAX
  #----------------------------------------------------------------------------
  def destroy
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.destroy
        format.js  # destroy.js.rjs { render :js => 'alert(\'js\');' }
        format.xml  { head :ok }
      else
        flash[:warning] = t(:msg_cant_delete_product, @product.name)
        format.js  # destroy.js.rjs
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  private
  #----------------------------------------------------------------------------
  def get_products
    Product.find(:all)
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper

  #----------------------------------------------------------------------------
  def link_to_product_edit(product)
    link_to(t(:edit), edit_admin_product_path(product),
      :method => :get,
      :with   => "{ view: '#{@view}', previous: crm.find_form('edit_product') }",
      :remote => true
    )
  end

  #----------------------------------------------------------------------------
  def link_to_product_delete(product)
    link_to(t(:delete) + "!", admin_product_path(product),
      :method => :delete,
      :with   => "{ view: '#{@view}' }",
      :before => visual_effect(:highlight, dom_id(product), :startcolor => "#ffe4e1"),
      :remote => true
    )
  end

  #----------------------------------------------------------------------------
  def link_to_product_confirm(product)
    link_to(t(:delete) + "!", confirm_admin_product_path(product),
      :with   => "{ view: '#{@view}' }",
      :before => visual_effect(:highlight, dom_id(product), :startcolor => "#ffe4e1"),
      :remote => true
    )
  end

end

app/views/admin/products/_confirm.html.haml
.confirm[@product, :confirm]
  #{t :product_confirm_delete}
  #{t :delete} <b>#{@product.name}</b>?
  = link_to(t(:yes_button), admin_product_path(@product), :method => :delete, :remote => true) << " : "
  = link_to_function(t(:no_button), "crm.flick('#{dom_id(@product, :confirm)}', 'remove')")

app/views/admin/products/_create.html.haml
= form_for([:admin, @product], :html => one_submit_only(:product), :remote => true) do |f|
  = link_to_close new_admin_product_path
  = f.error_messages :object_name => t('product')
  = render :partial => "admin/products/form", :locals => { :f => f }
  .buttonbar
    = f.submit t(:create_product)
    #{t :or}
    = link_to_cancel new_admin_product_path

app/views/admin/products/_edit.html.haml
.remote
  = simple_form_for(@product, :html => one_submit_only(:product), :url => admin_product_path(@product), :remote => true) do |f|
    = link_to_close edit_admin_product_path(@product)
    = f.error_messages
    = render :partial => "admin/products/form", :locals => { :f => f, :edit => true }
    .buttonbar
      = f.submit t(:save_product)
      #{t :or}
      = link_to_cancel edit_admin_product_path(@product)

app/views/admin/products/_form.html.haml
- edit ||= false
.section
  %table(width=500 cellpadding=0 cellspacing=0)
    %tr
      %td(valign="top")
        .label.top.req #{t :name}:
        = f.text_field :name, :style => "width:240px"
    %tr
      %td(valign="top")
        .label #{t :description}:
        = f.text_area :description, :style =>"width:240px", :rows => 4

app/views/admin/products/_product.html.haml
%li[product]{ highlightable(dom_id(product, :tools)) }

  .indentfull
    .tools{ invisible, :id => dom_id(product, :tools) }
      = link_to_product_edit(product) << " | "
      = link_to_product_confirm(product)


    %span.black #{product.name}
    %tt
      = "- #{h(product.description)}" unless product.description.blank?

    %dt{ :style => "padding: 2px 0px 0px 0px" }
      %span.warn #{t(:product_created_on, product.created_at.to_date.to_s(:ddmmyy))}

app/views/admin/products/index.html.haml
= styles_for :product

.title_tools
  = link_to_inline(:create_product, new_admin_product_path, :text => t(:create_product))

.title
  %span#create_product_title #{t(:product_title)}
.remote#create_product{ hidden }

.list#products= render :partial => "product", :collection => @products